### ISSUE TITLE
Using  System.Text.Json instead

### ISSUE THREAD

**Issue by baoduy** [proudmonkey/AutoWrapper#15]
As  System.Text.Json had been instroduced from .Net Core 3.0. May I submit an request to migrate Json serialization from Newtonsoft.Json to  System.Text.Json

**Comment by proudmonkey** [comment]
Hi @baoduy - Thanks for the feedback! Yes. Transitioning to System.Text.Json is part of my road map. In fact I've created [AutoWrapper.Server](https://www.nuget.org/packages/AutoWrapper.Server/1.0.0-rc) which is an unwrapper handler for AutoWrapper response in the server that uses `System.Text.Json`. :)

**Comment by baoduy** [comment]
Hi @proudmonkey 
I were took a look on your code. Let’s see if I could able to submit some PR as the code should have unit tests to track the breaking changes as well.

**Comment by proudmonkey** [comment]
@baoduy Just an FYI. I can't seem to find any document that shows how to create a custom contract resolver for `System.Text.Json` and `AutoWrapper` uses `CustomContactResolver` from Newtonsoft.json.

**Comment by baoduy** [comment]
You are right, And We are stuck there

**Comment by Vouzamo** [comment]
What about using a converter factory as shown here: https://weblogs.thinktecture.com/pawel/2019/10/aspnet-core-3-0-custom-jsonconverter-for-the-new-system_text_json.html

**Comment by proudmonkey** [comment]
@Vouzamo Interesting stuff there. I'll see what i can do. Thanks for sharing the link! :)

**Comment by mjftechnology** [comment]
Looking forward to this enhancement :)

**Comment by Vikaskumargd** [comment]
@proudmonkey  Looking forward to this enhancement 😊

**Comment by proudmonkey** [comment]
All - I've released an RC version just to test out the migration to .NET 5. Alot of code refactoring has been done for v5 and there are breaking changes. I would really appreciate if you could test it out as well: https://www.nuget.org/packages/AutoWrapper.Core/5.0.0-rc

Please provide feedback if there are any issues you encountered. Thank you!

# Breaking changes
* This release only supports .NET 5
* Middleware has been renamed from `UseApiResponseAndExceptionWrapper` to `UseAutoWrapper`. Make sure to update your `Startup.cs` to use the new name.
* `ProblemDetails` is now the default exception format
* Removed `Newtonsoft.Json` dependency and replaced it with `System.Text.Json`
* Use the interface `IApiResponse` model instead of the concrete `ApiResponse` model for returning responses using the default format. This allows you to add your own properties that will wrapped within the `Result` property. 
* `AutoWrapIgnore` and `RequestDataLogIgnore` attributes now leaves under `AutoWrapper.Attributes` namespace. The implementation was changed from using `IActionFilter` to use `Attribute`, eliminating all the request header logic.
* The following options has been removed:
   * ApiVersion
   * ReferenceLoopHandling
   * UseCustomSchema

> `ReferenceLoopHandling` and `DefaultContractResolver` aren't still supported in .NET 5 that's why handling reference loop and `ApiResponse` property mappings will not be supported when targetting .NET 5.
> .NET Core 3.1 will still use Newtonsoft.Json and it's only supported by AutoWrapper <= v4.5.0
